don't just give up on errors

diff --git a/bin/oo b/bin/oo
--- a/bin/oo
+++ b/bin/oo
@@ -1,18 +1,16 @@
 #!/bin/bash
 
-if [ -z "$1" ]; then
-	exit 1
-fi
-
-if [ ! -f "$1" ]; then
-	echo "file not found: $1"
-	exit 1
-fi
+[ -z "$1" ] && exit 1
 
 exec 2> /dev/null	# Turn off stderr
 
 for i in "$@"; do
 	[ -d "$i" ] && continue
+
+	if [ ! -f "$i" ]; then
+		echo "file not found: $i"
+		continue
+	fi
 
 	case "$i" in
 		*.doc|*.odt|*.rtf|*.ott)
